# Generated by Django 5.0.6 on 2025-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentledger',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
