# Generated by Django 5.2.4 on 2025-11-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feecategory'),
        ('payments', '0002_studentledger_reference_number'),
        ('students', '0007_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.feecategory'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='installment_frequency',
            field=models.PositiveIntegerField(default=30, help_text='Days between installments'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplan',
            unique_together={('student', 'academic_year', 'fee_category')},
        ),
    ]
