# Generated by Django 5.2.4 on 2026-01-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='registration_fee_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='session_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('full_day', 'Full Day')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('held', 'On Hold')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('quarterly', 'Quarterly'), ('full', 'Full Payment'), ('custom', 'Custom')], max_length=20),
        ),
    ]
