# Generated by Django 6.0.1 on 2026-02-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_paymentinstallment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("full_day", "Full Day"),
                    ("half_day", "Half Day"),
                    ("morning_nursery", "Morning Nursery"),
                    ("full_day_nursery", "Full Day Nursery"),
                    ("afternoon_nursery", "Afternoon Nursery"),
                    ("extended_nursery", "Extended Nursery"),
                    ("weekly_3_days", "Weekly 3 Days"),
                ],
                default="morning",
                max_length=20,
            ),
        ),
    ]
