# Generated by Django 5.0.6 on 2025-09-19 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('passport', 'Passport Copy'), ('emirates_id', 'Emirates ID'), ('medical_records', 'Medical Records'), ('previous_school_records', 'Previous School Records'), ('photo', 'Passport Photo'), ('other', 'Other')], max_length=30)),
                ('document', models.FileField(upload_to='student_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='student',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.AlterUniqueTogether(
            name='emergencycontact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_last_na_3e473b_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_year_gr_844b66_idx',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='middle_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='county',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='allergies',
            new_name='languages_spoken',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='passport_number',
            new_name='po_box_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='visa_status',
            new_name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_medical_info',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_ehcp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_sen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='intended_start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_school_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sen_details',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_group',
        ),
        migrations.AddField(
            model_name='student',
            name='age_at_enrollment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='child_emirates_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/child/'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='days_per_week',
            field=models.CharField(choices=[('2_days', '2 Days'), ('3_days', '3 Days'), ('4_days', '4 Days'), ('5_days', '5 Days'), ('6_days', '6 Days'), ('full_week', 'Full Week')], default='5_days', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_nationality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/father/'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_place_of_work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='father_position_held',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='father_work_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='first_contact_person',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_contact_relationship',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_contact_telephone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='full_home_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='home_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_required',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mother_nationality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mother_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/mother/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_place_of_work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_position_held',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_work_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='second_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='second_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='second_contact_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='siblings_info',
            field=models.TextField(blank=True, help_text='Sibling names and ages'),
        ),
        migrations.AddField(
            model_name='student',
            name='term_to_begin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='Dubai', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
