# Generated by Django 5.0.6 on 2025-09-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentdocument_studentnote_remove_document_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20, null=True),
        ),
    ]
