# Generated by Django 5.0.6 on 2025-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='term_to_begin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
