# Generated by Django 5.0.6 on 2025-09-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_classrooms'),
        ('students', '0004_alter_student_term_to_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.classrooms'),
        ),
    ]
