# Generated by Django 6.0.1 on 2026-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
