# Generated by Django 6.0.1 on 2026-02-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_student_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="child_emirates_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_mobile",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_work_telephone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_contact_telephone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="home_telephone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_mobile",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_work_telephone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="second_contact_telephone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
