# Generated by Django 5.0.6 on 2025-10-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_income_bill_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
    ]
