# Generated by Django 6.0.1 on 2026-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_rename_expence_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
    ]
