# Generated by Django 5.0.6 on 2025-10-06 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('emirates_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('po_box', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(choices=[('nursery_teacher', 'Nursery Teacher'), ('assistant_teacher', 'Assistant Teacher'), ('head_teacher', 'Head Teacher'), ('manager', 'Manager'), ('admin_staff', 'Administrative Staff'), ('support_staff', 'Support Staff')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reporting_to', models.CharField(default='Nursery Manager', max_length=100)),
                ('work_location', models.CharField(default='Blossom British Kids Center, Al Jurf, Ajman', max_length=200)),
                ('working_hours_start', models.TimeField(default='08:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('working_days', models.CharField(default='Monday to Saturday', max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('accommodation_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('probation_period_months', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annual_leave_days', models.IntegerField(default=30)),
                ('highest_qualification', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('certifications', models.TextField(blank=True, help_text='List all relevant certifications')),
                ('languages_spoken', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('cv_document', models.FileField(blank=True, null=True, upload_to='teacher_documents/cv/')),
                ('qualification_certificates', models.FileField(blank=True, null=True, upload_to='teacher_documents/certificates/')),
                ('emirates_id_copy', models.FileField(blank=True, null=True, upload_to='teacher_documents/emirates_id/')),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='teacher_documents/passport/')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('reference_1_name', models.CharField(blank=True, max_length=100)),
                ('reference_1_contact', models.CharField(blank=True, max_length=100)),
                ('reference_2_name', models.CharField(blank=True, max_length=100)),
                ('reference_2_contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_probation', 'On Probation'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='on_probation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('offer_accepted', models.BooleanField(default=True)),
                ('offer_acceptance_date', models.DateField(blank=True, null=True)),
                ('contract_signed', models.BooleanField(default=False)),
                ('contract_signed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher/Staff',
                'verbose_name_plural': 'Teachers/Staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
