# Generated by Django 5.2.4 on 2025-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_leaverequest_attendance_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('sick_leave', 'Sick Leave'), ('half_day', 'Half Day'), ('sunday', 'Sunday (Weekly Off)')], max_length=20),
        ),
    ]
